In [4]:
import numpy as np

In [13]:
x = np.array([[3,-3],[3,-6],[9,-3],[9,-6]])

In [15]:
y = np.array([[-(1/3), 0],[0,(1/3)]] )

In [18]:
np.dot(x,y)

array([[-1., -1.],
       [-1., -2.],
       [-3., -1.],
       [-3., -2.]])

In [ ]:
[23, 0.75]
[6, 1.75]

In [10]:
x = np.array( ((2,3), (3, 5)) )

ValueError: only 2 non-keyword arguments accepted

In [9]:
np.mat(x)

matrix([[2, 3],
        [3, 5]])

In [7]:
np.array([0,0,1])

array([0, 0, 1])

In [3]:
[[3,-3],[3,-6],[9,-3],[9,-6]] * [[-(1/3), 0],[0,(1/3)]] 

TypeError: can't multiply sequence by non-int of type 'list'